---
- name: instalar nginx
  hosts: web
  become: true
  roles:
    - web 
  vars:
    prueba: false 

  tasks:
  - name: nginx_check1
    ansible.builtin.import_tasks: tasks/nginx_check.yml
    tags: nginx_check
    #wmsonhen: prueba == true

  - name: test
    ansible.builtin.include_tasks: tasks/test.yml
    tags: test
    when: prueba == true

  - name: Crea txt
    ansible.builtin.copy:
      content: "Este servidor es de PRODUCCIÓN"
      dest: /var/www/html/production.txt
    when: web_environment == "producción"

  - name: Crea txt2
    ansible.builtin.copy:
      content: "Este servidor NO es PRODUCCION"
      dest: /var/www/html/development.txt
    when: web_environment != "producción"
 

  - name: Instalar varios paquetes
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
    loop:
      - curl
      - vim
      - tree

  - name: Crear varios directorios  
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
    loop:
      - /opt/lab
      - /opt/lab/logs
      - /opt/lab/config	

  - name: Crear varios archivos
    ansible.builtin.copy: 
      content: "{{ item.contenido }}"
      dest: "{{ item.ruta }}"
    loop:
      - ruta: /opt/lab/config/app.conf
        contenido: "Configuración de la aplicación"

      - ruta: /opt/lab/config/database.conf
        contenido: "Configuración de la base de datos"

      - ruta: /opt/lab/logs/app.log
        contenido: "logs inicializados por ansible"

  - name: loop con condiciones
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
    loop:
      - htop

  - name: loop en produccion
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
    loop:
      - ncdu
    when: web_environment == "producción"

  - name: loop mas variable
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
    loop: "{{ web_packages }}"

  - name: verificar el resultado generado 
    ansible.builtin.command:
      cmd: cat /var/www/html/index.html
    register: comprobante
    changed_when: false

  - name: Mostrar comprobante
    ansible.builtin.debug:
      msg: "{{ comprobante.stdout }}"
