---
- name: instalar nginx
  hosts: web
  become: true

  tasks:
  - name: Instalar nginx
    ansible.builtin.apt:
      name: nginx
      state: present
  
  - name: Crea página Web
    ansible.builtin.copy:
      content: "Servidor: {{ ansible_hostname }}\n{{ web_message }}\n{{ web_environment }}"
      dest: /var/www/html/index.html
    notify: reinicia nginx

  - name: Crea txt
    ansible.builtin.copy:
      content: "Este servidor es de PRODUCCIÓN"
      dest: /var/www/html/production.txt
    when: web_environment == "producción"

  - name: Crea txt2
    ansible.builtin.copy:
      content: "Este servidor NO es PRODUCCION"
      dest: /var/www/html/development.txt
    when: web_environment != "producción"
 
  - name: activar nginx
    ansible.builtin.service:
      name: nginx
      enabled: yes

  - name: Arrancar nginx
    ansible.builtin.service:
      name: nginx 
      state: started

  - name: Comprobar si existe nginx
    ansible.builtin.command:
      cmd: ls -lrt /usr/sbin/nginx
    register: nginx_check

  - name: Mostrar el resultado de que existe nginx 
    ansible.builtin.debug:
      msg: "{{ nginx_check.rc }}"
  
  - name: Condicion basada en el resultado
    ansible.builtin.debug:
      msg: "nginx esta instalado en este servidor"
    when: nginx_check.rc == 0

  - name: Condicion inversa
    ansible.builtin.debug:
      msg: "nginx no esta instalado en este servidor"
    when: nginx_check.rc != 0

  - name: Comprobar versión de nginx en producción
    ansible.builtin.command:
      cmd: nginx -v
    register: comprobacion
    when: web_environment == "producción"

  - name: Mostrar comprobación de nginx en producción
    ansible.builtin.debug:
      var: comprobacion
    when: web_environment == "producción"
 

  handlers:
    - name: reinicia nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
