---
- name: instalar nginx
  hosts: web
  become: true
  roles:
    - web 
  vars:
    prueba: false 

  tasks:
  - name: nginx_check1
    ansible.builtin.import_tasks: tasks/nginx_check.yml
    tags: nginx_check
    #when: prueba == true

  - name: test
    ansible.builtin.include_tasks: tasks/test.yml
    tags: test
    when: prueba == true

  - name: Crea txt
    ansible.builtin.copy:
      content: "Este servidor es de PRODUCCIÓN"
      dest: /var/www/html/production.txt
    when: web_environment == "producción"

  - name: Crea txt2
    ansible.builtin.copy:
      content: "Este servidor NO es PRODUCCION"
      dest: /var/www/html/development.txt
    when: web_environment != "producción"
 

  - name: Instalar varios paquetes
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
    loop:
      - curl
      - vim
      - tree

  - name: Crear varios directorios  
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
    loop:
      - /opt/lab
      - /opt/lab/logs
      - /opt/lab/config	

  - name: Crear varios archivos
    ansible.builtin.copy: 
      content: "{{ item.contenido }}"
      dest: "{{ item.ruta }}"
    loop:
      - ruta: /opt/lab/config/app.conf
        contenido: "Configuración de la aplicación"

      - ruta: /opt/lab/config/database.conf
        contenido: "Configuración de la base de datos"

      - ruta: /opt/lab/logs/app.log
        contenido: "logs inicializados por ansible"

  - name: loop con condiciones
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
    loop:
      - htop

  - name: loop en produccion
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
    loop:
      - ncdu
    when: web_environment == "producción"

  - name: loop mas variable
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
    loop: "{{ web_packages }}"

  - name: verificar el resultado generado 
    ansible.builtin.command:
      cmd: cat /var/www/html/index.html
    register: comprobante
    changed_when: false

  - name: Mostrar comprobante
    ansible.builtin.debug:
      msg: "{{ comprobante.stdout }}"

  - name: Crear usuario ansibleuser
    ansible.builtin.user:
      name: ansibleuser
      comment: usuario de pruebas
      shell: /bin/bash
    tags: user

  - name: Comprobar que usuario ansibleuser existe
    ansible.builtin.shell:
      cmd: grep ansibleuser /etc/passwd
    register: user_check
    tags: user

  - name: Comprobazzione usuario
    ansible.builtin.debug:
      msg: "{{ user_check.stdout }}"
    tags: user

  - name: Crear grupo ansibleadmins
    ansible.builtin.group:
      name: ansibladmins
      state: present
    tags: user

  - name: añadir ansible user a ansibladmins
    ansible.builtin.user:
      name: ansibleuser
      groups: ansibladmins
      append: yes
    tags: user

  - name: Comprobar que grupo ansibleadmins existe
    ansible.builtin.shell:
      cmd: cat /etc/group |grep ansibladmins 
    register: group_check
    tags: user
  
  - name: Comprobazzione group
    ansible.builtin.debug:
      msg: "{{ group_check.stdout }}"
    tags: user

  - name: Crear usuario con loop
    ansible.builtin.user:
      name: "{{ item }}"
      shell: /bin/bash
      groups: ansibladmins
      append: yes
    loop:
      - sysuser1
      - sysuser2
    tags: user

  - name: Comprobar que grupo ansibleadmins existe
    ansible.builtin.shell:
      cmd: cat /etc/group |grep ansibladmins 
    register: group_check
    tags: user
  
  - name: Comprobazzione group
    ansible.builtin.debug:
      msg: "{{ group_check.stdout }}"
    tags: user

  - name: Crear users con la combi completa
    ansible.builtin.user:
      name: "{{ item }}"
      shell: /bin/bash
      groups: ansibladmins
      append: yes
    loop: "{{ web_users }}"
    when: web_environment == "producción"
    tags: user

  - name: Comprobar que grupo ansibleadmins existe
    ansible.builtin.shell:
      cmd: cat /etc/group |grep ansibladmins 
    register: group_check
    tags: user
  
  - name: Comprobazzione group
    ansible.builtin.debug:
      msg: "{{ group_check.stdout }}"
    tags: user

